# Generated by Django 5.0.1 on 2024-02-16 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('S_NO', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('short_description', models.TextField()),
                ('image_url', models.URLField()),
                ('type', models.CharField(max_length=50)),
                ('calories', models.FloatField()),
                ('total_fat', models.FloatField()),
                ('saturated_fat', models.FloatField()),
                ('trans_fat', models.FloatField()),
                ('cholesterol', models.FloatField()),
                ('sodium', models.FloatField()),
                ('carbohydrate', models.FloatField()),
                ('dietary_fiber', models.FloatField()),
                ('sugar', models.FloatField()),
                ('protein', models.FloatField()),
                ('calcium', models.FloatField()),
                ('iron', models.FloatField()),
                ('potassium', models.FloatField()),
                ('vitamin_a', models.FloatField()),
                ('vitamin_b1', models.FloatField()),
                ('vitamin_b2', models.FloatField()),
                ('vitamin_b3', models.FloatField()),
                ('vitamin_b4', models.FloatField()),
                ('vitamin_b5', models.FloatField()),
                ('vitamin_b6', models.FloatField()),
                ('vitamin_b9', models.FloatField()),
                ('vitamin_b12', models.FloatField()),
                ('vitamin_c', models.FloatField()),
                ('vitamin_d', models.FloatField()),
                ('vitamin_e', models.FloatField()),
                ('vitamin_k', models.FloatField()),
                ('phosphorus', models.FloatField()),
                ('magnesium', models.FloatField()),
                ('zinc', models.FloatField()),
                ('copper', models.FloatField()),
                ('recommended_portion', models.FloatField()),
            ],
        ),
    ]
